routes/web.php
<?php

use Illuminate\Support\Facades\Route;

Route::get("/", "Front\PageController@getIndex");
Route::get("/home", "HomeController@index");


//******************************************User*****************************************

Route::middleware("auth")->prefix("/inventory")->group(function () {
    Route::resource("/category", "Inventory\CategoryController");
    Route::resource("/subcategory", "Inventory\SubCategoryController");

    Route::get("/order-request", "ProductOrderController@index")->name("order.index");
    Route::get("/product-order/{id}", "ProductOrderController@show")->name("order.show");
    Route::delete("/order/{id}", "ProductOrderController@destroy")->name("order.delete");
    Route::resource("/product", "Inventory\ProductController", ['except'=>['show']]);
    Route::get("product/newly_arrival", "Inventory\ProductController@newly_arrival")->name("product.newly_arrival");
    Route::get("product/special_offer", "Inventory\ProductController@special_offer")->name("product.special_offer");

    Route::resource('/size', "Inventory\SizeController", ['except'=>['create','edit','show']]);

    Route::get("/stock-history", "Inventory\StockController@history")->name("stock.history");
    Route::put("/stock-update/{id}", "Inventory\StockController@insert")->name("stock.insert");
    Route::resource("/stock", "Inventory\StockController");

    Route::get("/transaction-cancel/{id}", "Inventory\TransactionController@cancel")->name("transaction.cancel");

    Route::get("/transaction/product", "Inventory\ProductTransactionController@index")->name("product.transaction.index");
    Route::get("/transaction/product-search", "Inventory\ProductTransactionController@search");
    Route::get("/transaction/product/{id}", "Inventory\ProductTransactionController@show");

    Route::get("/transaction/report", "Inventory\TransactionController@history")->name("transaction.report");
    Route::get("/sell-history", "Inventory\TransactionController@index")->name("transaction.index");
    Route::resource("/transaction", "Inventory\TransactionController", ['except'=>['show','edit','index']]);


    Route::get("/user-transaction", "Inventory\UserTransactionController@index")->name("user.transaction.index");
    Route::post("/user-transaction", "Inventory\UserTransactionController@store");
    Route::get("/user-transaction/{user}", "Inventory\UserTransactionController@show");

    Route::resource("/quality", "Inventory\QualityController");
});
//******************************************User*****************************************

//******************************************Admin start*****************************************

Route::middleware("auth")->prefix("/admin")->as("admin.")->group(function () {
    Route::resource("/slider", "Front\SliderController", [
       "except"=>[
           'show'
       ]
   ]);

    Route::resource("/worker", "LeaderShipController", [
       'except'=>'show'
   ]);


    Route::resource("/feedback", "Front\FeedbackController");
    Route::resource("/event", "EventController");
    Route::resource("/latest_activities", "LatestActivitiesController");
    Route::resource("/production_units", "ProductionUnitsController");
    Route::resource("/business", "BusinessController");
    Route::resource("/business_category", "BusinessCategoryController");
    Route::resource("/event", "EventController");
    Route::resource("/gallery", "ImageUploadController");
//    Route::get('gallery','ImageUploadController@index');
    Route::get('gallery/create','ImageUploadController@fileCreate');
    Route::post('gallery/store','ImageUploadController@fileStore');
    Route::post('gallery/delete','ImageUploadController@fileDestroy');

    Route::get("/about-us", "HomeController@getAboutAdmin")->name("about");
    Route::post("/about-overview", "HomeController@storeAboutOverview")->name("about.overview");
    Route::get("/core-value", "HomeController@getCoreValue")->name("core");
    Route::post("/core-value", "HomeController@storeCoreValue")->name("core.store");
    Route::get("/contact", "ContactController@index")->name("contact.index");
    Route::get("/message/{id}", "ContactController@show");
    Route::delete("/message/{id}", "ContactController@destroy");

    Route::get("/company-detail", "CompanyDetailController@index")->name("company.detail");
    Route::post("/company-detail", "CompanyDetailController@store")->name("company.detail.store");

    Route::get("/send-mail","MailController@create");
    Route::post("/send-mail","MailController@store");

    Route::get("/mission", "HomeController@getMission")->name("mission");
    Route::post("/mission", "HomeController@storeMission")->name("mission.store");

    Route::get("/vision", "HomeController@getVision")->name("vision");
    Route::post("/vision", "HomeController@storeVision")->name("vision.store");

    Route::get("/objective", "HomeController@getObjective")->name("objective");
    Route::post("/objective", "HomeController@storeObjective")->name("objective.store");
});
//******************************************Admin End*****************************************


//******************************************Public*****************************************

Route::get("/about", "Front\PageController@getAbout");

Route::get("/products", "Front\ProductController@index");
Route::get("/product/{id}", "Front\ProductController@show")->name("public.product.show");
Route::get("/newly_arrived", "Front\ProductController@newly_arrival");
Route::get("/special_offer", "Front\ProductController@special_offer");
Route::get("/testimonial", "Front\PageController@getTestimonial");

Route::get("/vision", "Front\PageController@getvision");
Route::get("/mission", "Front\PageController@getMission");
Route::get("/objective", "Front\PageController@getobjective");
Route::get("/production_units", "Front\PageController@getProductionUnit");
Route::get("/latest_activity", "Front\PageController@getLatestActivities");
Route::get("/upcoming_event", "Front\PageController@getEvents");

Route::get("/search", "Front\ProductController@search");
Route::get("/categories", "Front\CategoryController@index");
Route::get("/subcategory/{id}", "Front\PageController@getProductsBySubCategory");

Route::post("/product-order", "ProductOrderController@store")->name("order.store");

Route::resource("/user", "UserController")->middleware("auth");

Route::get("/contact", "Front\PageController@getContact");
Route::post("/contact", "Front\PageController@storeContact");

Route::get("/login","Auth\LoginController@showLoginForm")->name("login");
Route::post("/login","Auth\LoginController@login");
Route::post("/logout","Auth\LoginController@logout")->name("logout");
Route::get("/StakeHolder","Front\PageController@getStakeHolder");
Route::get("/Stake/{id}","Front\PageController@getStake");
Route::get("/DealWithPatner","Front\PageController@getDealWithPatner");
Route::get("/DealWithPatnerid/{id}","Front\PageController@getDealWithPatnerId");
Route::get("/gallery","Front\PageController@getGallery");


//******************************************Public end*****************************************
/* **************************desigm part starts Here ************************************* */


Route::prefix("/design")->group(function() {


    Route::get("/check", function () {
        return view("public.pages.contact");
    });


    Route::get("/newly", function () {
        return view("design.newlyarrive");
    });
    Route::get("/category", function () {
        return view("design.category");
    });
    Route::get("/newly", function () {
        return view("design.newlyarrive");
    });
    Route::get("/vision", "Front\PageController@getvision");
    Route::get("/mission", "Front\PageController@getMission");
    Route::get("/objective", "Front\PageController@getobjective");
//    Route::get("/mission", function () {
//        return view("design.mission");
//    });

    Route::get("/upcoming_event", function () {
        return view("design.upcoming_event");
    });

    Route::get("/unit", function () {
        return view("design.unit");
    });
    Route::get("/activity", function () {
        return view("design.latest_activity");
    });
    Route::get("/gallery", function () {
        return view("design.gallery");
    });
    Route::get("/special", function () {
        return view("design.special_offer");
    });


    Route::get("/addevent", function () {
        return view("design.addevents");
    });
    Route::get("/feedback", function () {
        return view("design.customer_feedback");
    });
    Route::get("/stakeholder", function () {
        return view("design.stake_holder");
    });
    Route::get("/deal", function () {
        return view("design.deal_partner");
    });




});

resources/views/admin/gallery/create.blade.php
@extends("layouts.inventory")

@section("content")
    <meta name="_token" content="{{csrf_token()}}" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/dropzone/5.4.0/min/dropzone.min.css">
    <div class="col-sm-12 m-t-5 m-b-5">
        <a href="{{url("admin/gallery")}}" class="btn btn-primary">All Images</a>
    </div>
    <div class="container">
    <h3 class="jumbotron"> Images Upload </h3>
    <form method="post" action="{{url('admin/gallery/store')}}" enctype="multipart/form-data"
          class="dropzone" id="dropzone">
        {{csrf_field()}}
    </form>
</div>

@endsection
@section("script")
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/dropzone/5.4.0/dropzone.js"></script>
    <script >
        Dropzone.options.dropzone =
            {
                maxFilesize: 12,
                renameFile: function(file) {
                    var dt = new Date();
                    var time = dt.getTime();
                    return time+file.name;
                },
                acceptedFiles: ".jpeg,.jpg,.png,.gif",
                addRemoveLinks: true,
                timeout: 50000,
                removedfile: function(file)
                {
                    var name = file.upload.filename;
                    $.ajax({
                        headers: {
                            'X-CSRF-TOKEN': $('meta[name="_token"]').attr('content')
                        },
                        type: 'POST',
                        url: '{{ url("admin/gallery/delete") }}',
                        data: {filename: name},
                        success: function (data){
                            console.log("File has been successfully removed!!");
                        },
                        error: function(e) {
                            console.log(e);
                        }});
                    var fileRef;
                    return (fileRef = file.previewElement) != null ?
                        fileRef.parentNode.removeChild(file.previewElement) : void 0;
                },

                success: function(file, response)
                {
                    console.log(response);
                },
                error: function(file, response)
                {
                    return false;
                }
            };
    </script>
@endsection

resources/views/admin/gallery/edit.blade.php
@extends("layouts.inventory")
@section("styles")
    <link href="http://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.8/summernote.css" rel="stylesheet">
@endsection
@section("content")
    <div class="row white-box m-t-20">
        <div class="col-sm-12 m-t-5 m-b-5">
            <a href="{{url("admin/gallery/create")}}" class="btn btn-primary">Add Images</a>
            <a href="{{route("admin.gallery.index")}}" class="btn btn-primary">All Images</a>
        </div>
        <h2 class="page-header text-center">Edit Id:{{$galleries->id}} </h2>
        <div class="col-sm-10">
            <form method="post" action="{{route("admin.gallery.update",$galleries->id)}}" class="form-horizontal" enctype="multipart/form-data">
                {{csrf_field()}}
                {{method_field("put")}}

                <img src="{{asset('/images/gallery/'.$galleries->filename)}}" class="img img-responsive" height="200" width="200">
                <div class="form-group{{ $errors->has('file') ? ' has-error' : '' }}">
                    <label for="file" class="col-md-2 control-label">Image </label>

                    <div class="col-md-10">
                        <input id="file" type="file" class="form-control" name="file"  >

                        @if ($errors->has('file'))
                            <span class="help-block">
                                        <strong>{{ $errors->first('file') }}</strong>
                                    </span>
                        @endif
                    </div>
                </div>
                <div class="form-group{{ $errors->has('description') ? ' has-error' : '' }}">
                    <label for="description" class="col-md-2 control-label">Description</label>

                    <div class="col-md-10">
                        <textarea id="summernote" name="note">{{$galleries->description}}</textarea>

                        @if ($errors->has('description'))
                            <span class="help-block">
                                        <strong>{{ $errors->first('description') }}</strong>
                                    </span>
                        @endif
                    </div>
                </div>
                <div class="form-group">
                    <input type="submit" class="btn btn-success pull-right" value="update">
                </div>

            </form>
        </div>
    </div>

@endsection

@section("script")
    <script src="http://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.8/summernote.js"></script>
    <script>
        $(document).ready(function() {
            $('#summernote').summernote({
                height: 300,
                toolbar: [
                    // [groupName, [list of button]]
                    ['style', ['bold', 'italic', 'underline', 'clear']],
                    ['font', ['strikethrough', 'superscript', 'subscript']],
                    ['fontsize', ['fontsize']],
                    ['color', ['color']],
                    ['para', ['ul', 'ol', 'paragraph']],
                    ['height', ['height']]
                ]
            });
        });
    </script>
@endsection

resources/views/admin/gallery/index.blade.php
@extends("layouts.inventory")
@section("content")
    <div class="row">
        <div class="col-sm-12 m-t-5 m-b-5">
            <a href="{{url("admin/gallery/create")}}" class="btn btn-primary">Add Images</a>
        </div>
        <div class="col-sm-12">
            <table class="table table-bordered table-responsive">
                <thead>
                <tr>
                    <th>#</th>
                    <th>Image</th>
                    <th>Description</th>
                    <th>Action</th>
                </tr>
                </thead>
                <tbody>
                @foreach($galleries as $gallery)
                    <tr>
                        <td>{{$gallery->id}}</td>
                        <td><img src="{{asset('/images/gallery/'.$gallery->filename)}}" class="img img-responsive" height="200" width="200"> </td>
                        <td>{{$gallery->description}} </td>
                        <td>
                            <a href="{{route("admin.gallery.edit",$gallery->id)}}" class="btn btn-success"> Edit</a>
                            <a href="#" onclick="deleteSlider('{{$gallery->id}}')" class="btn btn-danger">Delete</a>
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>
        </div>
        <div id="myModal" class="modal fade" role="dialog">
            <div class="modal-dialog">

                <!-- Modal content-->
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                        <h4 class="modal-title">Delete Image</h4>
                    </div>
                    <div class="modal-body">
                        <p>You are on the delete track this process is irreversible. Are you sure? </p>
                    </div>
                    <div class="modal-footer">
                        <form action="#" id="deleteSlider"  method="post">
                            {{csrf_field()}}
                            {{method_field("delete")}}
                            <button type="submit" class="btn btn-danger">Delete</button>
                            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                        </form>

                    </div>
                </div>

            </div>
        </div>
    </div>
@endsection

@section("script")
    <script>
        function deleteSlider(id) {
            $("#deleteSlider").attr("action","/admin/gallery/"+id);
            $("#myModal").modal("show")
        }
    </script>
@endsection