routes/web.php
<?php

use Illuminate\Support\Facades\Route;

Route::get("/", "Front\PageController@getIndex");
Route::get("/home", "HomeController@index");


//******************************************User*****************************************

Route::middleware("auth")->prefix("/inventory")->group(function () {
    Route::resource("/category", "Inventory\CategoryController");
    Route::resource("/subcategory", "Inventory\SubCategoryController");

    Route::get("/order-request", "ProductOrderController@index")->name("order.index");
    Route::get("/product-order/{id}", "ProductOrderController@show")->name("order.show");
    Route::delete("/order/{id}", "ProductOrderController@destroy")->name("order.delete");
    Route::resource("/product", "Inventory\ProductController", ['except'=>['show']]);
    Route::get("product/newly_arrival", "Inventory\ProductController@newly_arrival")->name("product.newly_arrival");
    Route::get("product/special_offer", "Inventory\ProductController@special_offer")->name("product.special_offer");

    Route::resource('/size', "Inventory\SizeController", ['except'=>['create','edit','show']]);

    Route::get("/stock-history", "Inventory\StockController@history")->name("stock.history");
    Route::put("/stock-update/{id}", "Inventory\StockController@insert")->name("stock.insert");
    Route::resource("/stock", "Inventory\StockController");

    Route::get("/transaction-cancel/{id}", "Inventory\TransactionController@cancel")->name("transaction.cancel");

    Route::get("/transaction/product", "Inventory\ProductTransactionController@index")->name("product.transaction.index");
    Route::get("/transaction/product-search", "Inventory\ProductTransactionController@search");
    Route::get("/transaction/product/{id}", "Inventory\ProductTransactionController@show");

    Route::get("/transaction/report", "Inventory\TransactionController@history")->name("transaction.report");
    Route::get("/sell-history", "Inventory\TransactionController@index")->name("transaction.index");
    Route::resource("/transaction", "Inventory\TransactionController", ['except'=>['show','edit','index']]);


    Route::get("/user-transaction", "Inventory\UserTransactionController@index")->name("user.transaction.index");
    Route::post("/user-transaction", "Inventory\UserTransactionController@store");
    Route::get("/user-transaction/{user}", "Inventory\UserTransactionController@show");

    Route::resource("/quality", "Inventory\QualityController");
});
//******************************************User*****************************************

//******************************************Admin start*****************************************

Route::middleware("auth")->prefix("/admin")->as("admin.")->group(function () {
    Route::resource("/slider", "Front\SliderController", [
       "except"=>[
           'show'
       ]
   ]);

    Route::resource("/worker", "LeaderShipController", [
       'except'=>'show'
   ]);


    Route::resource("/feedback", "Front\FeedbackController");
    Route::resource("/event", "EventController");
    Route::resource("/latest_activities", "LatestActivitiesController");
    Route::resource("/production_units", "ProductionUnitsController");
    Route::resource("/business", "BusinessController");
    Route::resource("/business_category", "BusinessCategoryController");
    Route::resource("/event", "EventController");
    Route::resource("/gallery", "ImageUploadController");
//    Route::get('gallery','ImageUploadController@index');
    Route::get('gallery/create','ImageUploadController@fileCreate');
    Route::post('gallery/store','ImageUploadController@fileStore');
    Route::post('gallery/delete','ImageUploadController@fileDestroy');

    Route::get("/about-us", "HomeController@getAboutAdmin")->name("about");
    Route::post("/about-overview", "HomeController@storeAboutOverview")->name("about.overview");
    Route::get("/core-value", "HomeController@getCoreValue")->name("core");
    Route::post("/core-value", "HomeController@storeCoreValue")->name("core.store");
    Route::get("/contact", "ContactController@index")->name("contact.index");
    Route::get("/message/{id}", "ContactController@show");
    Route::delete("/message/{id}", "ContactController@destroy");

    Route::get("/company-detail", "CompanyDetailController@index")->name("company.detail");
    Route::post("/company-detail", "CompanyDetailController@store")->name("company.detail.store");

    Route::get("/send-mail","MailController@create");
    Route::post("/send-mail","MailController@store");

    Route::get("/mission", "HomeController@getMission")->name("mission");
    Route::post("/mission", "HomeController@storeMission")->name("mission.store");

    Route::get("/vision", "HomeController@getVision")->name("vision");
    Route::post("/vision", "HomeController@storeVision")->name("vision.store");

    Route::get("/objective", "HomeController@getObjective")->name("objective");
    Route::post("/objective", "HomeController@storeObjective")->name("objective.store");
});
//******************************************Admin End*****************************************


//******************************************Public*****************************************

Route::get("/about", "Front\PageController@getAbout");

Route::get("/products", "Front\ProductController@index");
Route::get("/product/{id}", "Front\ProductController@show")->name("public.product.show");
Route::get("/newly_arrived", "Front\ProductController@newly_arrival");
Route::get("/special_offer", "Front\ProductController@special_offer");
Route::get("/testimonial", "Front\PageController@getTestimonial");

Route::get("/vision", "Front\PageController@getvision");
Route::get("/mission", "Front\PageController@getMission");
Route::get("/objective", "Front\PageController@getobjective");
Route::get("/production_units", "Front\PageController@getProductionUnit");
Route::get("/latest_activity", "Front\PageController@getLatestActivities");
Route::get("/upcoming_event", "Front\PageController@getEvents");

Route::get("/search", "Front\ProductController@search");
Route::get("/categories", "Front\CategoryController@index");
Route::get("/subcategory/{id}", "Front\PageController@getProductsBySubCategory");

Route::post("/product-order", "ProductOrderController@store")->name("order.store");

Route::resource("/user", "UserController")->middleware("auth");

Route::get("/contact", "Front\PageController@getContact");
Route::post("/contact", "Front\PageController@storeContact");

Route::get("/login","Auth\LoginController@showLoginForm")->name("login");
Route::post("/login","Auth\LoginController@login");
Route::post("/logout","Auth\LoginController@logout")->name("logout");
Route::get("/StakeHolder","Front\PageController@getStakeHolder");
Route::get("/Stake/{id}","Front\PageController@getStake");
Route::get("/DealWithPatner","Front\PageController@getDealWithPatner");
Route::get("/DealWithPatnerid/{id}","Front\PageController@getDealWithPatnerId");
Route::get("/gallery","Front\PageController@getGallery");


//******************************************Public end*****************************************
/* **************************desigm part starts Here ************************************* */


Route::prefix("/design")->group(function() {


    Route::get("/check", function () {
        return view("public.pages.contact");
    });


    Route::get("/newly", function () {
        return view("design.newlyarrive");
    });
    Route::get("/category", function () {
        return view("design.category");
    });
    Route::get("/newly", function () {
        return view("design.newlyarrive");
    });
    Route::get("/vision", "Front\PageController@getvision");
    Route::get("/mission", "Front\PageController@getMission");
    Route::get("/objective", "Front\PageController@getobjective");
//    Route::get("/mission", function () {
//        return view("design.mission");
//    });

    Route::get("/upcoming_event", function () {
        return view("design.upcoming_event");
    });

    Route::get("/unit", function () {
        return view("design.unit");
    });
    Route::get("/activity", function () {
        return view("design.latest_activity");
    });
    Route::get("/gallery", function () {
        return view("design.gallery");
    });
    Route::get("/special", function () {
        return view("design.special_offer");
    });


    Route::get("/addevent", function () {
        return view("design.addevents");
    });
    Route::get("/feedback", function () {
        return view("design.customer_feedback");
    });
    Route::get("/stakeholder", function () {
        return view("design.stake_holder");
    });
    Route::get("/deal", function () {
        return view("design.deal_partner");
    });




});

app/Http/Controllers/Inventory/CategoryController.php
<?php

namespace App\Http\Controllers\Inventory;

use App\Model\Category;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Session;
use Intervention\Image\Facades\Image;
class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @param Request $request
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {

        $categories=Category::select("id","name","image")->get();
        return view("inventory.category.index",compact("categories"));
    }

    /**
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function create(){
        return view("inventory.category.create");
    }


    public function edit($id){
        $category=Category::findorfail($id);
        return view("inventory.category.edit",compact("category"));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        $this->validate($request,[
            "name"=>"required|max:255|unique:categories,name",

        ]);

//        $file=$request->file("image");
//        $filename=uniqid(true).'.png';
//        $db_location='images/categories/'.$filename;
//
//        $location=public_path('images/categories/'.$filename);
//
//        Image::make($file)->encode("png")->resize(640, 360, function ($constraint) {
//            $constraint->aspectRatio();
//        })->save($location);

        Category::create([
            "name"=>$request->get("name"),
            "image"=>"image"
        ]);

        Session::flash("success","Category is created");

        return redirect()->route("category.index");

    }


    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $category=Category::findorfail($id);
        $this->validate($request,[
            "name"=>"required|unique:categories,name,".$category->id,
            "image"=>"nullable|mimes:jpg,jpeg,png"
        ]);
//        if($request->hasFile("image")){
//            $old_location=public_path($category->image);
//
//            if(file_exists($old_location))
//                unlink($old_location);
//
//            $file=$request->file("image");
//            $filename=uniqid(true).'.png';
//            $db_location='images/categories/'.$filename;
//
//            $location=public_path('images/categories/'.$filename);
//
//            Image::make($file)->encode("png")->resize(640, 360, function ($constraint) {
//                $constraint->aspectRatio();
//            })->save($location);
//                    $category->update([
//            "name"=>$request->get("name"),
//                        "image"=>$db_location
//        ]);

//        }else{
            $category->update([
                "name"=>$request->get("name")]);
//        }

        Session::flash("success","Category updated successfully");
        return redirect()->back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $category=Category::findorfail($id);
        $location=public_path($category->image);

        if(file_exists($location))
            unlink($location);

        $category->delete();

        Session::flash("success","Category has been deleted");

        return redirect()->back();
    }
}

app/Http/Controllers/Inventory/ProductTransactionController.php
<?php

namespace App\Http\Controllers\Inventory;

use App\Model\Product;
use App\Model\StockRecord;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class ProductTransactionController extends Controller
{
    /**
     * @param Request $request
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index(Request $request){
      if($request->has("query")){
          $products=Product::select("id","name")->where("name","like",'%'.$request->get("query").'%')->orderBy("name","asc")->get();
      }else{
          $products=Product::select("id","name")->orderBy("name","asc")->get();
      }

        return view("inventory.transaction.product.index",compact("products"));
    }

    public function show($id){
        $product=Product::select("id","name","category_id","subcategory_id","code","image","price")->find($id);

       $records =StockRecord::select("size_name","user_name","bought_price","quantity","code","created_at")->where("product_id",$id)->get()->map(function ($item){
            return[

               "size"=> $item->size_name,
                "user_name"=>$item->user_name,
                "price"=>$item->bought_price,
                 "quantity"=>$item->quantity,
                "code"=>$item->code,
                "created_at"=>$item->created_at->toDateString()
            ];
        });
//  $records =StockRecord::select("size_name","user_name","bought_price","quantity","code","created_at")->where("product_id",$id)->get();


        return view("inventory.transaction.product.show",compact("records","product"));
    }


    public function search(Request $request){
        $id=$request->get("id");
        if($request->has("query")){
            $query=$request->get("query");

            $records=StockRecord::select("size_name","user_name","bought_price","quantity","code","created_at")
                ->where([["user_name","like",'%'.$query.'%'],["product_id",$id]])
                ->orWhere([["code","like",'%'.$query.'%'],["product_id",$id]])
                ->get()->map(function ($item){
                return[

                    "size"=> $item->size_name,
                    "user_name"=>$item->user_name,
                    "price"=>$item->bought_price,
                    "quantity"=>$item->quantity,
                    "code"=>$item->code,
                    "created_at"=>$item->created_at->toDateString()
                ];
            });

            return response()->json($records,200);
        }
        if($request->has("time")){
            $time=$request->get("time");
            $records=StockRecord::select("size_name","user_name","bought_price","quantity","code","created_at")
                ->where("product_id",$id)
                ->WhereDate("created_at","=",$time)
                ->get()->map(function ($item){
                return[

                    "size"=> $item->size_name,
                    "user_name"=>$item->user_name,
                    "price"=>$item->bought_price,
                    "quantity"=>$item->quantity,
                    "code"=>$item->code,
                    "created_at"=>$item->created_at->toDateString()
                ];
            });

            return response()->json($records,200);
        }


    }


}

resources/views/inventory/subcategory/create.blade.php
@extends("layouts.inventory")

@section("content")
    <div class="row" >

        <div class="col-md-12 ">

            <a href="{{route("subcategory.index")}}" class="btn btn-primary m-b-10" >All subcategories</a>
            <div class="white-box">


                <h3 class="page-header">New subcategory</h3>

                <form class="form-horizontal" method="POST" action="{{ route('subcategory.store') }}" enctype="multipart/form-data">
                    {{ csrf_field() }}

                    <div class="form-group{{ $errors->has('category') ? ' has-error' : '' }}">
                        <label for="category" class="col-md-2 control-label">Category </label>

                        <div class="col-md-10">
                            <select name="category" class="form-control" id="category">
                                <option value="0">Select a category</option>
                                @foreach($categories as $category)
                                    <option value="{{$category->id}}">{{$category->name}}</option>
                                @endforeach
                            </select>

                            @if ($errors->has('category'))
                                <span class="help-block">
                                        <strong>{{ $errors->first('category') }}</strong>
                                    </span>
                            @endif
                        </div>
                    </div>
                    <div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
                        <label for="name" class="col-md-2 control-label"> Name </label>

                        <div class="col-md-10">
                            <input id="name" type="text" class="form-control" name="name" value="{{ old('name') }}" required autofocus>

                            @if ($errors->has('name'))
                                <span class="help-block">
                                        <strong>{{ $errors->first('name') }}</strong>
                                    </span>
                            @endif
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-8 col-md-offset-4">
                            <button type="submit" class="btn btn-primary">
                                Create subcategory
                            </button>


                        </div>
                    </div>
                </form>
            </div>


            {{--<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myModal">Add new Category</button>--}}

        </div>



    </div>
@endsection

resources/views/inventory/subcategory/edit.blade.php
@extends("layouts.inventory")

@section("content")
    <div class="row" >

        <div class="col-md-12 ">

            <a href="{{route("subcategory.index")}}" class="btn btn-primary m-b-10" >All subcategories</a>
            <div class="white-box">


                <h3 class="page-header">Update subcategory</h3>

                <form class="form-horizontal" method="POST" action="{{ route('subcategory.update',$subcategory->id) }}" >
                    {{ csrf_field() }}
                    {{method_field("PUT")}}

                    <div class="form-group{{ $errors->has('category') ? ' has-error' : '' }}">
                        <label for="category" class="col-md-2 control-label">Category </label>

                        <div class="col-md-10">
                            <select name="category" class="form-control" id="category">
                                <option value="0">Select a category</option>
                                @foreach($categories as $category)
                                    <option value="{{$category->id}}" {!! $category->id==$subcategory->category_id?'selected':''!!}>{{$category->name}}</option>
                                @endforeach
                            </select>

                            @if ($errors->has('category'))
                                <span class="help-block">
                                        <strong>{{ $errors->first('category') }}</strong>
                                    </span>
                            @endif
                        </div>
                    </div>
                    <div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
                        <label for="name" class="col-md-2 control-label"> Name </label>

                        <div class="col-md-10">
                            <input id="name" type="text" class="form-control" name="name" value="{{ $subcategory->name }}" required autofocus>

                            @if ($errors->has('name'))
                                <span class="help-block">
                                        <strong>{{ $errors->first('name') }}</strong>
                                    </span>
                            @endif
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-8 col-md-offset-4">
                            <button type="submit" class="btn btn-primary">
                                Update subcategory
                            </button>


                        </div>
                    </div>
                </form>
            </div>


            {{--<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myModal">Add new Category</button>--}}

        </div>



    </div>
@endsection

resources/views/inventory/subcategory/index.blade.php
@extends("layouts.inventory")

@section("content")
    <div class="row" >

        <div class="col-md-12 ">

            <a href="{{route("subcategory.create")}}" class="btn btn-primary" >Add a new subcategory</a>

            {{--<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myModal">Add new Category</button>--}}

            <table class="table table-responsive white-box m-t-20" v-cloak>
                <thead>
                <tr>
                    <th>#</th>

                    <th>Name</th>

                    <th>Action</th>
                </tr>
                </thead>
                <tbody>
                <tr v-for="subcategory in subcategories">
                    <td>@{{ subcategory.id }}</td>
                    <td>@{{ subcategory.name }}</td>

                    <td>
                        <a class="btn btn-success"  :href="'/inventory/subcategory/'+subcategory.id+'/edit'" >Edit</a>
                        <button class="btn btn-danger" @click="deletesubcategory(subcategory.id)">Delete</button> </td>
                </tr>
                </tbody>
            </table>

            <!-- Modal -->
            <div id="myModal" class="modal fade" role="dialog">
                <div class="modal-dialog">
                    <div class="modal-content">

                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                            <h4 class="modal-title" id="myModalLabel">Create Category</h4>
                        </div>
                        <form  method="post" action="{{route("category.store")}}" enctype="multipart/form-data">
                            {{csrf_field()}}
                            <div class="modal-body">
                                <div class="row">
                                    <div class="col-sm-12">
                                        <div class="form-group">
                                            <label for="">Name</label>
                                            <input type="text" class="form-control" id=""  placeholder="Name" required="true" name="name">
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div class="modal-footer">
                                <button type="button" class="btn btn-default" data-dismiss="modal" >Cancel</button>
                                <input type="submit" class="btn btn-success" value="Create">
                            </div>
                        </form>
                    </div>
                </div>
            </div>

            <div id="myDeleteModal" class="modal fade" role="dialog">
                <div class="modal-dialog">
                    <div class="modal-content">

                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                            <h4 class="modal-title" id="myModalLabel">Delete  </h4>
                        </div>
                        <form  method="post" :action="deleteUrl" >
                            {{csrf_field()}}
                            {{method_field("Delete")}}
                            <div class="modal-body">
                                <div class="row">
                                    <div class="col-sm-12">
                                        You are on the delete track . This process is irreversible . Are you sure?
                                    </div>
                                </div>
                            </div>

                            <div class="modal-footer">
                                <button type="button" class="btn btn-default" data-dismiss="modal" >Cancel</button>
                                <input type="submit" class="btn btn-danger" value="Delete">
                            </div>
                        </form>
                    </div>
                </div>
            </div>

        </div>



    </div>
@endsection

@section("script")
    <script>
        new Vue({
            el:'#wrapper',
            data:{
                subcategories:{!! json_encode($subcategories) !!},
                editUrl:'',
                categoryName:'',
                deleteUrl:'',
            },
            methods:{
                editCategory:function (id,name) {
                    this.categoryName=name;
                    this.editUrl='/inventory/subcategory/'+id;
                    $("#myUpdateModal").modal("show")

                },
                deletesubcategory:function (id) {
                    this.deleteUrl='/inventory/subcategory/'+id;
                    $("#myDeleteModal").modal("show");

                }
            }
        })
    </script>

@endsection