routes/web.php
<?php

use Illuminate\Support\Facades\Route;

Route::get("/", "Front\PageController@getIndex");
Route::get("/home", "HomeController@index");


//******************************************User*****************************************

Route::middleware("auth")->prefix("/inventory")->group(function () {
    Route::resource("/category", "Inventory\CategoryController");
    Route::resource("/subcategory", "Inventory\SubCategoryController");

    Route::get("/order-request", "ProductOrderController@index")->name("order.index");
    Route::get("/product-order/{id}", "ProductOrderController@show")->name("order.show");
    Route::delete("/order/{id}", "ProductOrderController@destroy")->name("order.delete");
    Route::resource("/product", "Inventory\ProductController", ['except'=>['show']]);
    Route::get("product/newly_arrival", "Inventory\ProductController@newly_arrival")->name("product.newly_arrival");
    Route::get("product/special_offer", "Inventory\ProductController@special_offer")->name("product.special_offer");

    Route::resource('/size', "Inventory\SizeController", ['except'=>['create','edit','show']]);

    Route::get("/stock-history", "Inventory\StockController@history")->name("stock.history");
    Route::put("/stock-update/{id}", "Inventory\StockController@insert")->name("stock.insert");
    Route::resource("/stock", "Inventory\StockController");

    Route::get("/transaction-cancel/{id}", "Inventory\TransactionController@cancel")->name("transaction.cancel");

    Route::get("/transaction/product", "Inventory\ProductTransactionController@index")->name("product.transaction.index");
    Route::get("/transaction/product-search", "Inventory\ProductTransactionController@search");
    Route::get("/transaction/product/{id}", "Inventory\ProductTransactionController@show");

    Route::get("/transaction/report", "Inventory\TransactionController@history")->name("transaction.report");
    Route::get("/sell-history", "Inventory\TransactionController@index")->name("transaction.index");
    Route::resource("/transaction", "Inventory\TransactionController", ['except'=>['show','edit','index']]);


    Route::get("/user-transaction", "Inventory\UserTransactionController@index")->name("user.transaction.index");
    Route::post("/user-transaction", "Inventory\UserTransactionController@store");
    Route::get("/user-transaction/{user}", "Inventory\UserTransactionController@show");

    Route::resource("/quality", "Inventory\QualityController");
});
//******************************************User*****************************************

//******************************************Admin start*****************************************

Route::middleware("auth")->prefix("/admin")->as("admin.")->group(function () {
    Route::resource("/slider", "Front\SliderController", [
       "except"=>[
           'show'
       ]
   ]);

    Route::resource("/worker", "LeaderShipController", [
       'except'=>'show'
   ]);


    Route::resource("/feedback", "Front\FeedbackController");
    Route::resource("/event", "EventController");
    Route::resource("/latest_activities", "LatestActivitiesController");
    Route::resource("/production_units", "ProductionUnitsController");
    Route::resource("/business", "BusinessController");
    Route::resource("/business_category", "BusinessCategoryController");
    Route::resource("/event", "EventController");
    Route::resource("/gallery", "ImageUploadController");
//    Route::get('gallery','ImageUploadController@index');
    Route::get('gallery/create','ImageUploadController@fileCreate');
    Route::post('gallery/store','ImageUploadController@fileStore');
    Route::post('gallery/delete','ImageUploadController@fileDestroy');

    Route::get("/about-us", "HomeController@getAboutAdmin")->name("about");
    Route::post("/about-overview", "HomeController@storeAboutOverview")->name("about.overview");
    Route::get("/core-value", "HomeController@getCoreValue")->name("core");
    Route::post("/core-value", "HomeController@storeCoreValue")->name("core.store");
    Route::get("/contact", "ContactController@index")->name("contact.index");
    Route::get("/message/{id}", "ContactController@show");
    Route::delete("/message/{id}", "ContactController@destroy");

    Route::get("/company-detail", "CompanyDetailController@index")->name("company.detail");
    Route::post("/company-detail", "CompanyDetailController@store")->name("company.detail.store");

    Route::get("/send-mail","MailController@create");
    Route::post("/send-mail","MailController@store");

    Route::get("/mission", "HomeController@getMission")->name("mission");
    Route::post("/mission", "HomeController@storeMission")->name("mission.store");

    Route::get("/vision", "HomeController@getVision")->name("vision");
    Route::post("/vision", "HomeController@storeVision")->name("vision.store");

    Route::get("/objective", "HomeController@getObjective")->name("objective");
    Route::post("/objective", "HomeController@storeObjective")->name("objective.store");
});
//******************************************Admin End*****************************************


//******************************************Public*****************************************

Route::get("/about", "Front\PageController@getAbout");

Route::get("/products", "Front\ProductController@index");
Route::get("/product/{id}", "Front\ProductController@show")->name("public.product.show");
Route::get("/newly_arrived", "Front\ProductController@newly_arrival");
Route::get("/special_offer", "Front\ProductController@special_offer");
Route::get("/testimonial", "Front\PageController@getTestimonial");

Route::get("/vision", "Front\PageController@getvision");
Route::get("/mission", "Front\PageController@getMission");
Route::get("/objective", "Front\PageController@getobjective");
Route::get("/production_units", "Front\PageController@getProductionUnit");
Route::get("/latest_activity", "Front\PageController@getLatestActivities");
Route::get("/upcoming_event", "Front\PageController@getEvents");

Route::get("/search", "Front\ProductController@search");
Route::get("/categories", "Front\CategoryController@index");
Route::get("/subcategory/{id}", "Front\PageController@getProductsBySubCategory");

Route::post("/product-order", "ProductOrderController@store")->name("order.store");

Route::resource("/user", "UserController")->middleware("auth");

Route::get("/contact", "Front\PageController@getContact");
Route::post("/contact", "Front\PageController@storeContact");

Route::get("/login","Auth\LoginController@showLoginForm")->name("login");
Route::post("/login","Auth\LoginController@login");
Route::post("/logout","Auth\LoginController@logout")->name("logout");
Route::get("/StakeHolder","Front\PageController@getStakeHolder");
Route::get("/Stake/{id}","Front\PageController@getStake");
Route::get("/DealWithPatner","Front\PageController@getDealWithPatner");
Route::get("/DealWithPatnerid/{id}","Front\PageController@getDealWithPatnerId");
Route::get("/gallery","Front\PageController@getGallery");


//******************************************Public end*****************************************
/* **************************desigm part starts Here ************************************* */


Route::prefix("/design")->group(function() {


    Route::get("/check", function () {
        return view("public.pages.contact");
    });


    Route::get("/newly", function () {
        return view("design.newlyarrive");
    });
    Route::get("/category", function () {
        return view("design.category");
    });
    Route::get("/newly", function () {
        return view("design.newlyarrive");
    });
    Route::get("/vision", "Front\PageController@getvision");
    Route::get("/mission", "Front\PageController@getMission");
    Route::get("/objective", "Front\PageController@getobjective");
//    Route::get("/mission", function () {
//        return view("design.mission");
//    });

    Route::get("/upcoming_event", function () {
        return view("design.upcoming_event");
    });

    Route::get("/unit", function () {
        return view("design.unit");
    });
    Route::get("/activity", function () {
        return view("design.latest_activity");
    });
    Route::get("/gallery", function () {
        return view("design.gallery");
    });
    Route::get("/special", function () {
        return view("design.special_offer");
    });


    Route::get("/addevent", function () {
        return view("design.addevents");
    });
    Route::get("/feedback", function () {
        return view("design.customer_feedback");
    });
    Route::get("/stakeholder", function () {
        return view("design.stake_holder");
    });
    Route::get("/deal", function () {
        return view("design.deal_partner");
    });




});

app/User.php
<?php

namespace App;

use App\Model\UserTransaction;
use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function transactions(){
        return $this->hasMany(UserTransaction::class);
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Session;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users=User::select("id","name","email")->where("role",2)->get();

        return view("admin.user.index",compact("users"));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view("admin.user.create");
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request,[
            'name' => 'required|string|max:255',
            'email' => 'required|string|email|max:255|unique:users',
        ]);

        User::create([
            "name"=>$request->get("name"),
            "email"=>$request->get("email"),
            "password"=>Hash::make("password")
        ]);
        Session::flash("success","User created");


        return redirect()->route("user.index");
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $user=User::findorfail($id);

        return view("admin.user.edit",compact("user"));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $user=User::findorfail($id);

        $this->validate($request,[
            'name' => 'required|string|max:255',
            'email' => 'required|string|email|max:255|unique:users,email,'.$user->id,
        ]);



            $user->update([
                "name"=>$request->get("name"),
                "email"=>$request->get("email"),
            ]);

        Session::flash("success","User has been updated");

        return redirect()->back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $user=User::findorfail($id);
        $user->delete();
        Session::flash("success","User has been deleted");

        return back();
    }
}

resources/views/admin/user/create.blade.php
@extends("layouts.inventory")

@section("content")
    <div class="row" >

        <div class="col-md-12 ">

            <a href="{{route("user.index")}}" class="btn btn-primary m-b-10" >All users</a>
            <div class="white-box">


                <h3 class="page-header">New user</h3>

                <form class="form-horizontal" method="POST" action="{{ route('user.store') }}">
                    {{ csrf_field() }}

                    <div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
                        <label for="name" class="col-md-4 control-label">Name</label>

                        <div class="col-md-6">
                            <input id="name" type="text" class="form-control" name="name" value="{{ old('name') }}" required autofocus>

                            @if ($errors->has('name'))
                                <span class="help-block">
                                        <strong>{{ $errors->first('name') }}</strong>
                                    </span>
                            @endif
                        </div>
                    </div>

                    <div class="form-group{{ $errors->has('email') ? ' has-error' : '' }}">
                        <label for="email" class="col-md-4 control-label">E-Mail Address</label>

                        <div class="col-md-6">
                            <input id="email" type="email" class="form-control" name="email" value="{{ old('email') }}" required>

                            @if ($errors->has('email'))
                                <span class="help-block">
                                        <strong>{{ $errors->first('email') }}</strong>
                                    </span>
                            @endif
                        </div>
                    </div>

                    {{--<div class="form-group{{ $errors->has('password') ? ' has-error' : '' }}">--}}
                        {{--<label for="password" class="col-md-4 control-label">Password</label>--}}

                        {{--<div class="col-md-6">--}}
                            {{--<input id="password" type="password" class="form-control" name="password" required>--}}

                            {{--@if ($errors->has('password'))--}}
                                {{--<span class="help-block">--}}
                                        {{--<strong>{{ $errors->first('password') }}</strong>--}}
                                    {{--</span>--}}
                            {{--@endif--}}
                        {{--</div>--}}
                    {{--</div>--}}

                    {{--<div class="form-group">--}}
                        {{--<label for="password-confirm" class="col-md-4 control-label">Confirm Password</label>--}}

                        {{--<div class="col-md-6">--}}
                            {{--<input id="password-confirm" type="password" class="form-control" name="password_confirmation" required>--}}
                        {{--</div>--}}
                    {{--</div>--}}

                    <div class="form-group">
                        <div class="col-md-6 col-md-offset-4">
                            <button type="submit" class="btn btn-primary">
                                Create
                            </button>
                        </div>
                    </div>
                </form>
            </div>



        </div>



    </div>
@endsection

resources/views/admin/user/edit.blade.php
@extends("layouts.inventory")

@section("content")
    <div class="row" >

        <div class="col-md-12 ">

            <a href="{{route("user.index")}}" class="btn btn-primary m-b-10" >All users</a>
            <div class="white-box">


                <h3 class="page-header">Edit user : {{$user->name}}</h3>

                <form class="form-horizontal" method="POST" action="{{ route('user.update',$user->id) }}">
                    {{ csrf_field() }}
                    {{method_field("PUT")}}

                    <div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
                        <label for="name" class="col-md-4 control-label">Name</label>

                        <div class="col-md-6">
                            <input id="name" type="text" class="form-control" name="name" value="{{ $user->name }}" required autofocus>

                            @if ($errors->has('name'))
                                <span class="help-block">
                                        <strong>{{ $errors->first('name') }}</strong>
                                    </span>
                            @endif
                        </div>
                    </div>

                    <div class="form-group{{ $errors->has('email') ? ' has-error' : '' }}">
                        <label for="email" class="col-md-4 control-label">E-Mail Address</label>

                        <div class="col-md-6">
                            <input id="email" type="email" class="form-control" name="email" value="{{ $user->email  }}" required>

                            @if ($errors->has('email'))
                                <span class="help-block">
                                        <strong>{{ $errors->first('email') }}</strong>
                                    </span>
                            @endif
                        </div>
                    </div>

                    {{--<div class="form-group{{ $errors->has('password') ? ' has-error' : '' }}">--}}
                        {{--<label for="password" class="col-md-4 control-label">Password</label>--}}

                        {{--<div class="col-md-6">--}}
                            {{--<input id="password" type="password" class="form-control" name="password" >--}}

                            {{--@if ($errors->has('password'))--}}
                                {{--<span class="help-block">--}}
                                        {{--<strong>{{ $errors->first('password') }}</strong>--}}
                                    {{--</span>--}}
                            {{--@endif--}}
                        {{--</div>--}}
                    {{--</div>--}}

                    {{--<div class="form-group">--}}
                        {{--<label for="password-confirm" class="col-md-4 control-label">Confirm Password</label>--}}

                        {{--<div class="col-md-6">--}}
                            {{--<input id="password-confirm" type="password" class="form-control" name="password_confirmation" >--}}
                        {{--</div>--}}
                    {{--</div>--}}

                    <div class="form-group">
                        <div class="col-md-6 col-md-offset-4">
                            <button type="submit" class="btn btn-primary">
                                Update
                            </button>
                        </div>
                    </div>
                </form>
            </div>



        </div>



    </div>
@endsection

resources/views/admin/user/index.blade.php
@extends("layouts.inventory")

@section("content")
    <div class="row" >

        <div class="col-md-12 ">

            <a href="{{route("user.create")}}" class="btn btn-primary" >Add a new user</a>

            {{--<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myModal">Add new Category</button>--}}

            <table class="table table-responsive white-box m-t-20" v-cloak>
                <thead>
                <tr>
                    <th>#</th>

                    <th>Name</th>
                    <th>Email</th>
                    <th>Action</th>
                </tr>
                </thead>
                <tbody>
                <tr v-for="user in users">
                    <td>@{{ user.id }}</td>
                    <td>@{{ user.name }}</td>
                    <td>@{{ user.email }}</td>
                    <td>
                        <a class="btn btn-success"  :href="'/user/'+user.id+'/edit'" >Edit</a>
                        <button class="btn btn-danger" @click="deleteUser(user.id)">Delete</button> </td>
                </tr>
                </tbody>
            </table>

            <!-- Modal -->
            {{--<div id="myModal" class="modal fade" role="dialog">--}}
                {{--<div class="modal-dialog">--}}
                    {{--<div class="modal-content">--}}

                        {{--<div class="modal-header">--}}
                            {{--<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>--}}
                            {{--<h4 class="modal-title" id="myModalLabel">Create Category</h4>--}}
                        {{--</div>--}}
                        {{--<form  method="post" action="{{route("category.store")}}" enctype="multipart/form-data">--}}
                            {{--{{csrf_field()}}--}}
                            {{--<div class="modal-body">--}}
                                {{--<div class="row">--}}
                                    {{--<div class="col-sm-12">--}}
                                        {{--<div class="form-group">--}}
                                            {{--<label for="">Name</label>--}}
                                            {{--<input type="text" class="form-control" id=""  placeholder="Name" required="true" name="name">--}}
                                        {{--</div>--}}
                                    {{--</div>--}}
                                {{--</div>--}}
                            {{--</div>--}}

                            {{--<div class="modal-footer">--}}
                                {{--<button type="button" class="btn btn-default" data-dismiss="modal" >Cancel</button>--}}
                                {{--<input type="submit" class="btn btn-success" value="Create">--}}
                            {{--</div>--}}
                        {{--</form>--}}
                    {{--</div>--}}
                {{--</div>--}}
            {{--</div>--}}
            {{--<div id="myUpdateModal" class="modal fade" role="dialog">--}}
            {{--<div class="modal-dialog">--}}
            {{--<div class="modal-content">--}}

            {{--<div class="modal-header">--}}
            {{--<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>--}}
            {{--<h4 class="modal-title" id="myModalLabel">Update Category : @{{ categoryName }}</h4>--}}
            {{--</div>--}}
            {{--<form  method="post" :action="editUrl" >--}}
            {{--{{csrf_field()}}--}}
            {{--{{method_field("PUT")}}--}}
            {{--<div class="modal-body">--}}
            {{--<div class="row">--}}
            {{--<div class="col-sm-12">--}}
            {{--<div class="form-group">--}}
            {{--<label for="">Name</label>--}}
            {{--<input type="text" class="form-control" id=""  placeholder="Name" required="true" name="name" :value="categoryName">--}}
            {{--</div>--}}
            {{--</div>--}}
            {{--</div>--}}
            {{--</div>--}}

            {{--<div class="modal-footer">--}}
            {{--<button type="button" class="btn btn-default" data-dismiss="modal" >Cancel</button>--}}
            {{--<input type="submit" class="btn btn-success" value="Update">--}}
            {{--</div>--}}
            {{--</form>--}}
            {{--</div>--}}
            {{--</div>--}}
            {{--</div>--}}
            <div id="myDeleteModal" class="modal fade" role="dialog">
                <div class="modal-dialog">
                    <div class="modal-content">

                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                            <h4 class="modal-title" id="myModalLabel">Delete  </h4>
                        </div>
                        <form  method="post" :action="deleteUrl" >
                            {{csrf_field()}}
                            {{method_field("Delete")}}
                            <div class="modal-body">
                                <div class="row">
                                    <div class="col-sm-12">
                                        You are on the delete track . This process is irreversible . Are you sure?
                                    </div>
                                </div>
                            </div>

                            <div class="modal-footer">
                                <button type="button" class="btn btn-default" data-dismiss="modal" >Cancel</button>
                                <input type="submit" class="btn btn-danger" value="Delete">
                            </div>
                        </form>
                    </div>
                </div>
            </div>

        </div>



    </div>
@endsection

@section("script")
    <script>
        new Vue({
            el:'#wrapper',
            data:{
                users:{!! json_encode($users) !!},
                editUrl:'',
                categoryName:'',
                deleteUrl:'',
            },
            methods:{
                deleteUser:function (id) {
                    this.deleteUrl='/user/'+id;
                    $("#myDeleteModal").modal("show");

                }
            }
        })
    </script>

@endsection